import Head from "next/head";
import { useState } from "react"; // import Script from "next/script";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home(props) {
  const [blog, setblog] = useState(props.allBlogs);
  return (
    <div className={styles.container}>
      <Head>
        <title>Error Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="Next.js,Error,Blog,Web development" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src="/alert.js" strategy="lazyOnload"></Script> */}

      <main className={styles.main}>
        <h1 className={styles.title}>
          Error{" "}
          <a href="/" target="_blank">
            Blog
          </a>
        </h1>

        <p className={styles.description}>
          An Error Blog for learning Web Development
        </p>

        <h2>Latest Posts</h2>
        <br />

        <div className={styles.grid}>
          {blog.map((blogitems, index) => {
            return (
              index < 5 && (
                <div key={blogitems.slug}>
                  <Link href={`/blogposts/${blogitems.slug}`}>
                    <a className={styles.card}>
                      <h2>{blogitems.title} &rarr;</h2>
                      <p>{blogitems.metadesc.substr(0, 400)}</p>
                    </a>
                  </Link>
                </div>
              )
            );
          })}
        </div>
        {/* <div className={styles.grid}>
          <Link href="/blogposts/How-to-use-google-analytics-with-nextjs">
            <a className={styles.card}>
              <h2>How to use google analytics with next.js app? &rarr;</h2>
              <p>
                I'm using styled-components with next.js so my styles need to be
                server-side rendered, hence how can I add google analytics to my
                website? … I checked next.js google analytics example but as I
                said my...
              </p>
            </a>
          </Link>

          <Link href="/blogposts/Learn-Nextjs">
            <a className={styles.card}>
              <h2>Learn Nextjs &rarr;</h2>
              <p>
                I'm using styled-components with next.js so my styles need to be
                server-side rendered, hence how can I add google analytics to my
                website? … I checked next.js google analytics example but as I
                said my...
              </p>
            </a>
          </Link>

          <Link href="/blogposts/Learn-Reactjs">
            <a className={styles.card}>
              <h2>Learn Reactjs &rarr;</h2>
              <p>
                I'm using styled-components with next.js so my styles need to be
                server-side rendered, hence how can I add google analytics to my
                website? … I checked next.js google analytics example but as I
                said my...
              </p>
            </a>
          </Link>

          <Link href="/blogposts/Learn-Html">
            <a className={styles.card}>
              <h2>Learn Html &rarr;</h2>
              <p>
                I'm using styled-components with next.js so my styles need to be
                server-side rendered, hence how can I add google analytics to my
                website? … I checked next.js google analytics example but as I
                said my...
              </p>
            </a>
          </Link>

          <Link href="/blogposts/Learn-Css">
            <a className={styles.card}>
              <h2>Learn Css &rarr;</h2>
              <p>
                I'm using styled-components with next.js so my styles need to be
                server-side rendered, hence how can I add google analytics to my
                website? … I checked next.js google analytics example but as I
                said my...
              </p>
            </a>
          </Link>

          <Link href="/blogposts/Learn-Routing">
            <a className={styles.card}>
              <h2>Learn Routing &rarr;</h2>
              <p>
                I'm using styled-components with next.js so my styles need to be
                server-side rendered, hence how can I add google analytics to my
                website? … I checked next.js google analytics example but as I
                said my...
              </p>
            </a>
          </Link> 
        </div>*/}
      </main>
    </div>
  );
}
export async function getServerSideProps(context) {
  let data = await fetch("http://localhost:3000/api/blogs");
  let allBlogs = await data.json();

  return {
    props: { allBlogs }, // will be passed to the page component as props
  };
}
